# Generated by Django 5.2.7 on 2025-11-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('poster', models.TextField()),
                ('plot', models.TextField()),
                ('released', models.DateTimeField()),
                ('writer', models.TextField()),
                ('genre', models.TextField()),
                ('type', models.CharField()),
                ('year', models.DateField()),
            ],
        ),
    ]
