# Generated by Django 5.2.7 on 2025-11-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.TextField(),
        ),
    ]
