# Generated by Django 5.2.7 on 2025-11-11 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_released'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='plot',
            new_name='Plot',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='Poster',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='released',
            new_name='Released',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='writer',
            new_name='Writer',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='Year',
        ),
    ]
