# Generated by Django 5.2.7 on 2025-11-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_favoritelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favoritelists',
            field=models.ManyToManyField(to='movie.favoritelist'),
        ),
    ]
