# Generated by Django 5.2.7 on 2025-11-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_remove_movie_favoritelists_movie_favoritelists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favoritelists',
        ),
        migrations.AddField(
            model_name='favoritelist',
            name='movies',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
            preserve_default=False,
        ),
    ]
