# Generated by Django 5.2.7 on 2025-11-19 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_remove_movie_favoritelists_favoritelist_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritelist',
            name='movies',
            field=models.ForeignKey(default={}, on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
        ),
    ]
