# Generated by Django 5.2.7 on 2025-11-19 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_favoritelist_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritelist',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='favoritelist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.favoritelist'),
            preserve_default=False,
        ),
    ]
