# Generated by Django 5.2.7 on 2025-11-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_remove_favoritelist_movies_movie_favoritelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favoritelist',
        ),
        migrations.AddField(
            model_name='movie',
            name='favoritelist',
            field=models.ManyToManyField(to='movie.favoritelist'),
        ),
    ]
